//!Sleep function
function sleep(e){const t=Date.now();let n=null;do{n=Date.now()}while(n-t<e)}
//!Sleep function
//!On input idle -> Unfocus
function checkKey(e){"38"!=(e=e||window.event).keyCode&&"40"!=e.keyCode||document.activeElement.blur()}
//!On input idle -> Unfocus
//!Search Typing Funtion 
let typingTimer;document.onkeydown=checkKey;let doneTypingInterval=260,myInput=document.getElementById("searchTerm");function doneTyping(){const e=document.querySelector(".searchTerm"),t=document.querySelector(".UlDropdown");$(t).empty();var n="http://127.0.0.1:8000/api/product/search-products/"+e.value,l=new XMLHttpRequest;"http://127.0.0.1:8000/api/product/search-products/"!=n&&(l.open("GET",n),l.onreadystatechange=function(){if(4===l.readyState){JSON.parse(l.response).map((e=>{t.append(ul_func(e.product_name,e.variant_id))}))}},l.send())}function ul_func(e,t){let n=document.createElement("li");return n.classList.add("product_li"),null==e?(n.innerHTML="\n    Product Not Found",n):(n.id=`${t}`,n.innerHTML=`${e}`,n)}
//!Search Typing Funtion 
//!On Enter Search 
myInput.addEventListener("keyup",(function(e){e.preventDefault()}),!1),myInput.addEventListener("keyup",(()=>{clearTimeout(typingTimer),null!=myInput.value?typingTimer=setTimeout(doneTyping,doneTypingInterval):$(UlDropdown).empty()})),$(document).on("keypress","#searchTerm",(function(e){13!=e.keyCode&&"13"!=e.which||search()}));var button=document.getElementById("searchButton");function search(){const e=document.querySelector(".searchTerm");var t="http://127.0.0.1:8000/api/product/search-products/"+e.value,n=new XMLHttpRequest;n.open("GET",t),n.onreadystatechange=function(){if(4===n.readyState){let e=n.responseText;localStorage.setItem("searchdata",e),window.open("/order/order-min.html")}},n.send(),localStorage.setItem("searchTerm",e.value)}
//!On Enter Search 
//!Product Dropdown Selection 
let ul=document.getElementById("UlDropdown");var liSelected,index=-1;function removeClass(e,t){e.classList?e.classList.remove(t):e.className=e.className.replace(new RegExp("(^|\\b)"+t.split(" ").join("|")+"(\\b|$)","gi")," ")}function addClass(e,t){if(e.classList){e.classList.add(t);let n=e.id;localStorage.setItem("focus",n)}else e.className+=" "+t}
//!Product Dropdown Selection 
document.addEventListener("keydown",(function(e){var t=ul.getElementsByTagName("li").length-1;40===e.which?(index++,liSelected?(removeClass(liSelected,"selected"),next=ul.getElementsByTagName("li")[index],void 0!==typeof next&&index<=t?liSelected=next:(index=0,liSelected=ul.getElementsByTagName("li")[0]),addClass(liSelected,"selected")):(index=0,addClass(liSelected=ul.getElementsByTagName("li")[0],"selected"))):38===e.which&&(liSelected?(removeClass(liSelected,"selected"),index--,next=ul.getElementsByTagName("li")[index],void 0!==typeof next&&index>=0?liSelected=next:(index=t,liSelected=ul.getElementsByTagName("li")[t]),addClass(liSelected,"selected")):(index=0,addClass(liSelected=ul.getElementsByTagName("li")[t],"selected")))}),!1);